// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value | comment
    // 1 | open | /auth/login |  | 
    driver.get("http://103.120.226.190/auth/login");
    // 2 | setWindowSize | 550x692 |  | 
    driver.manage().window().setSize(new Dimension(550, 692));
    // 3 | click | name=username |  | 
    driver.findElement(By.name("username")).click();
    // 4 | click | name=username |  | 
    driver.findElement(By.name("username")).click();
    // 5 | type | name=username | 3017218053 | 
    driver.findElement(By.name("username")).sendKeys("3017218053");
    // 6 | click | name=password |  | 
    driver.findElement(By.name("password")).click();
    // 7 | type | name=password | https://gitee.com/chenkuochih/software_test.git | 
    driver.findElement(By.name("password")).sendKeys("https://gitee.com/chenkuochih/software_test.git");
    // 8 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 9 | click | name=username |  | 
    driver.findElement(By.name("username")).click();
    // 10 | type | name=username | 3017218054 | 
    driver.findElement(By.name("username")).sendKeys("3017218054");
    // 11 | click | name=password |  | 
    driver.findElement(By.name("password")).click();
    // 12 | type | name=password | https://gitee.com/roshan0/software_test.git | 
    driver.findElement(By.name("password")).sendKeys("https://gitee.com/roshan0/software_test.git");
    // 13 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 14 | click | css=html |  | 
    driver.findElement(By.cssSelector("html")).click();
    // 15 | click | css=html |  | 
    driver.findElement(By.cssSelector("html")).click();
    // 16 | click | css=html |  | 
    driver.findElement(By.cssSelector("html")).click();
    // 17 | click | css=.p-5 |  | 
    driver.findElement(By.cssSelector(".p-5")).click();
    // 18 | click | css=.p-5 |  | 
    driver.findElement(By.cssSelector(".p-5")).click();
    // 19 | close |  |  | 
    driver.close();
  }
}
